   name: Deploy docs
   on:
     push:
       branches: [main]
   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-python@v5
           with:
             python-version: 3.x
         - run: pip install mkdocs mkdocs-material mkdocs_puml mkdocs_puml_file mkdocs-render-swagger-plugin
         - run: mkdocs gh-deploy --force